background_opacity 0.4
font_family Maple Mono NF
font_size 10
cursor #ff79c6



color0 #15161e
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6
